version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  node:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
